var nome = prompt ('Nome');
document.getElementById('nome').innerHTML = nome;
// console.log(nome);
var cognome = prompt ('Cognome');
document.getElementById('cognome').innerHTML = cognome;
// console.log(cognome);
var colorePreferito = prompt ('Colore preferito');
document.getElementById('colore-preferito').innerHTML = colorePreferito;
// console.log(colorePreferito);
document.getElementById('container').setAttribute('class' , 'visible');
